# -------------------
# Jekyll Config
# --------------------
baseurl: ""
url: ""
permalink: pretty
markdown: kramdown
highlighter: rouge
collections_dir: collections

# Plugins
plugins:
  - jekyll-environment-variables
  - jekyll-paginate
  - jekyll-youtube

paginate: 6
paginate_path: "/blog/page/:num"

collections:
  services:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  team:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: ""
      type: services
    values:
      layout: service
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      weight: 999
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "categories"
    values:
      permalink: /category/:basename/
  - scope:
      path: "pages"
    values:
      permalink: /:basename/

# SCSS
sass:
  style: compact

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - netlify.toml


# -------------------
# Theme Config
# --------------------
title: "Honestywild"
category_dir: category

colors:
  #light-mode colors
  primary: "#295A52" #"#000000" #
  primary_2: "#393F3E"
  primary_text: "#fdfcf9"
  secondary: "#2f4c47"
  background: "#ffffff"
  background_2: "#EEF4F3"
  background_3: "#D5E2E0"
  text: "#272727"
  text_2: "#383838"

  # dark-mode colors
  primary_dark: "#759A93"
  primary_2_dark: "#131313"
  primary_text_dark: "#fdfcf9"
  secondary_dark: "#2f4c47"
  background_dark: "#131313"
  background_2_dark: "#131313"
  background_3_dark: "#222124"
  text_dark: "#EEF4F3"
  text_2_dark: "#D5E2E0"


fonts:
  google_fonts: "https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;700&display=swap"
  heading: "Noto Sans KR"
  base: "Noto Sans KR"
  monospace: "Noto Sans KR"
  logo: "Noto Sans KR"

logo:
  logo_text: "Honesty wild"
  logo_image: assets/images/logo/logo.svg
  logo_image_mobile: assets/images/logo/logo-mobile.svg
  logo_image_invert: assets/images/logo/logo-invert.svg
  logo_image_invert_mobile: assets/images/logo/logo-invert-mobile.svg
  logo_image_desktop_height: "58px"
  logo_image_desktop_width: "184px"
  logo_image_mobile_height: "30px"
  logo_image_mobile_width: "34px"
  show_logo_image_on_mobile: true
  show_logo_image_on_desktop: true
  show_logo_text_on_mobile: false
  show_logo_text_on_desktop: false
  
header: 
  fixed: true

darkmode:
  enable_dark_mode: true
  show_dark_mode_toggle_in_header: false
  show_dark_mode_toggle_in_bottom: true
  show_dark_mode_toggle_in_mobile_menu: true

analytics:
  google_analytics_id: ""

disqus:
  shortname: "" # Your disqus shortcode. leave this blank to disable comments globally

mailchimp:
  form_action_url: https://zerostatic.us13.list-manage.com/subscribe/post?u=675276692aebec1c007f8156d&amp;id=3e3da720c2

contact_form: 
  use_netlify_form: true
  use_formspree_form: false
  formspree_endpoint: https://formspree.io/f/moqyklqv

menu: 
  show_dropdown_items_in_mobile_menu: false
  show_social_media_in_mobile_menu: true

footer:
  enable_footer: true # show/hide the entire footer
  footer_title: "주식회사 어니스티와일드"
  footer_description: "Honesty Wild Inc."
  enable_social_media_icons: true
  enable_contact_details: true
  enable_menu_footer_primary: true
  enable_menu_footer_secondary: true
  enable_menu_footer_tertiary: true
  footer_primary_menu_title: "Product"
  footer_secondary_menu_title: "Company"
  footer_tertiary_menu_title: "Other"

bottom:
  enable_bottom: true # show/hide the entire bottom (below the footer)
  enable_bottom_menu: true # if enabled, the bottom menu can be edited in `_data/menu.yml`
  copyright_text: "© 2021 Zerostatic Themes"

sidebar:
  enable_sidebar_services: true
  enable_breadcrumbs_services: true
  enable_sidebar_projects: false
  enable_breadcrumbs_projects: true

